apiVersion: v1
kind: Secret
metadata:
  name: crypto
  namespace: chaos-app
type: Opaque
stringData:
  coinbase-token: TODO
  messari-token: TODO
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-crypto
  namespace: chaos-app
  labels:
    app: provider-crypto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: provider-crypto
  template:
    metadata:
      labels:
        app: provider-crypto
    spec:
      containers:
        - name: provider-crypto
          image: docker.io/korpatiy/finance-dashboard-provider-crypto:v0.3.3-dev
          env:
            - name: CRYPTO_DELAY
              value: "11000"
            - name: CRYPTO_GRPC_PORT
              value: "9092"
            - name: CRYPTO_PORT
              value: "9091"
            - name: CRYPTO_COINS
              value: "btc;eth;bnb;usdt;sol"
            - name: CRYPTO_COINBASE_KEY
              valueFrom:
                secretKeyRef:
                  name: crypto
                  key: coinbase-token
            - name: CRYPTO_MESSARI_KEY
              valueFrom:
                secretKeyRef:
                  name: crypto
                  key: messari-token
          ports:
            - containerPort: 9091
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: provider-crypto
  namespace: chaos-app
spec:
  selector:
    app: provider-crypto
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082
