apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chaos-app
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/iskorotkov/finance-dashboard-frontend:v0.1.3-dev
          env:
            - name: NODE_ENV
              value: production
            - name: REACT_APP_PROVIDERS
              value: Stocks=ws://34.118.80.181/stocks/api/v1/stocks;Stocks (foreign)=ws://34.118.80.181/stocks-foreign/api/v1/stocks;Crypto=ws://34.118.80.181/crypto/api/v1/coins
            - name: REACT_APP_PREDICTION_SERVICE
              value: http://34.118.80.181/scheduler
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chaos-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
